/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:3271e19b-9c4c-48d1-8460-2d495f088043",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_97bcxM4Ce",
    "aws_user_pools_web_client_id": "1eqk005mh2c05e2pcc6h3q7tll",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ifympn6zqnfntmbjmlh5f5v7a4.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4wdbu5rk5jf3flivmxlpyebqti",
    "aws_user_files_s3_bucket": "foodstock55100-staging",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
